from rest_framework import serializers
from .models import Event, EventStatus, BroadcastSession, ViewerSession, EventLogin


# ---------------------------------------------------------------------------
# Event
# ---------------------------------------------------------------------------

class EventListSerializer(serializers.ModelSerializer):
    created_by_name = serializers.SerializerMethodField()
    concurrent_viewers = serializers.SerializerMethodField()
    playback_urls = serializers.SerializerMethodField()

    class Meta:
        model = Event
        fields = [
            "id", "title", "description", "status",
            "scheduled_start", "scheduled_end",
            "stream_start_time", "playback_urls",
            "created_by_name", "concurrent_viewers",
            "created_at",
        ]

    def get_created_by_name(self, obj):
        return f"{obj.created_by.first_name} {obj.created_by.last_name}"

    def get_concurrent_viewers(self, obj):
        return obj.viewer_sessions.filter(left_at=None).count()

    def get_playback_urls(self, obj):
        return list(obj.broadcast_sessions.values_list("playback_url", flat=True))


class EventDetailSerializer(EventListSerializer):
    broadcast_sessions = serializers.SerializerMethodField()

    class Meta(EventListSerializer.Meta):
        # "scheduled_end" intentionally not repeated here — it's already
        # inherited from EventListSerializer.Meta.fields
        fields = [field for field in EventListSerializer.Meta.fields if field != "playback_urls"] + [
            "video_muted_by_default", "pause_continue_enabled",
            "stream_end_time", "recording_url",
            "broadcast_sessions", "updated_at",
        ]

    def get_broadcast_sessions(self, obj):
        request = self.context.get("request")
        return [
            self._broadcast_session_data(session, request)
            for session in obj.broadcast_sessions.all()
        ]

    def _broadcast_session_data(self, session, request):
        data = {
            "id": session.id,
            "name": session.name,
            "is_primary": session.is_primary,
            "is_active": session.is_active,
            "playback_url": session.playback_url,
            "started_at": session.started_at,
            "ended_at": session.ended_at,
        }

        if request and request.user.is_authenticated and (
            request.user == session.broadcaster
            or request.user.role in ("EVENT_ADMIN", "SUPER_ADMIN")
        ):
            data.update({
                "stream_key": session.stream_key,
                "ingest_url": session.ingest_url,
                "started_at": session.started_at,
            })
        return data


class EventCreateUpdateSerializer(serializers.ModelSerializer):
    class Meta:
        model = Event
        fields = [
            "id",
            "title", "description", "scheduled_start", "scheduled_end",
            "video_muted_by_default", "pause_continue_enabled",
        ]
        read_only_fields = ["id"]

    def create(self, validated_data):
        validated_data["created_by"] = self.context["request"].user
        return super().create(validated_data)


# ---------------------------------------------------------------------------
# BroadcastSession
# ---------------------------------------------------------------------------

class BroadcastSessionSerializer(serializers.ModelSerializer):
    event_title = serializers.CharField(source="event.title", read_only=True)
    broadcaster_name = serializers.SerializerMethodField()

    class Meta:
        model = BroadcastSession
        fields = [
            "id", "event", "event_title", "broadcaster", "broadcaster_name",
            "name", "is_primary", "stream_key", "ingest_url", "playback_url",
            "is_active", "started_at", "ended_at", "created_at",
        ]
        read_only_fields = [
            "stream_key", "ingest_url", "playback_url",
            "is_active", "started_at", "ended_at", "created_at",
        ]

    def get_broadcaster_name(self, obj):
        return f"{obj.broadcaster.first_name} {obj.broadcaster.last_name}"


class BroadcastSessionCreateSerializer(serializers.ModelSerializer):
    """Minimal input — stream_key/ingest_url/playback_url are generated by
    BroadcastSession.save() itself, never accepted from the client."""

    class Meta:
        model = BroadcastSession
        fields = [
            "id", "event", "broadcaster", "name", "is_primary",
            "stream_key", "ingest_url", "playback_url",
        ]
        read_only_fields = ["stream_key", "ingest_url", "playback_url"]

    def create(self, validated_data):
        event = validated_data["event"]
        if not event.broadcast_sessions.exists():
            validated_data["is_primary"] = True
        return super().create(validated_data)


# ---------------------------------------------------------------------------
# ViewerSession
# ---------------------------------------------------------------------------

class ViewerSessionSerializer(serializers.ModelSerializer):
    user_name = serializers.SerializerMethodField()
    watch_duration_minutes = serializers.SerializerMethodField()

    class Meta:
        model = ViewerSession
        fields = [
            "id", "user", "user_name", "event",
            "joined_at", "left_at", "is_active",
            "watch_duration_seconds", "watch_duration_minutes",
            "last_heartbeat",
        ]
        read_only_fields = fields

    def get_user_name(self, obj):
        return f"{obj.user.first_name} {obj.user.last_name}"

    def get_watch_duration_minutes(self, obj):
        return round(obj.watch_duration_seconds / 60, 1)


class ViewerJoinSerializer(serializers.Serializer):
    event_id = serializers.IntegerField()
    event_title = serializers.CharField()
    broadcast_sessions = BroadcastSessionSerializer(many=True)
    viewer_session_id = serializers.IntegerField()
    concurrent_viewers = serializers.IntegerField()
    video_muted_by_default = serializers.BooleanField()


# ---------------------------------------------------------------------------
# Webhook (inbound from media server)
# ---------------------------------------------------------------------------

class StreamWebhookSerializer(serializers.Serializer):
    ACTIONS = ["stream.started", "stream.ended", "stream.error"]

    action = serializers.ChoiceField(choices=ACTIONS)
    stream_key = serializers.CharField()
    timestamp = serializers.DateTimeField(required=False)

    def validate_stream_key(self, value):
        try:
            self._broadcast_session = BroadcastSession.objects.select_related("event").get(
                stream_key=value
            )
        except BroadcastSession.DoesNotExist:
            raise serializers.ValidationError("Invalid stream key.")
        return value

    @property
    def broadcast_session(self):
        return self._broadcast_session


# ---------------------------------------------------------------------------
# Analytics
# ---------------------------------------------------------------------------

class EventAnalyticsSerializer(serializers.Serializer):
    event_id = serializers.IntegerField()
    event_title = serializers.CharField()
    status = serializers.CharField()
    total_joins = serializers.IntegerField()
    concurrent_viewers = serializers.IntegerField()
    peak_viewers = serializers.IntegerField()
    avg_watch_duration_minutes = serializers.FloatField()
    stream_duration_minutes = serializers.FloatField(allow_null=True)


class UpcomingEventSerializer(serializers.ModelSerializer):
    is_registered = serializers.BooleanField(read_only=True)

    class Meta:
        model = Event
        fields = "__all__"
